### ISSUE TITLE
Webpack Error?

### ISSUE THREAD

**Issue by diverjasongray** [PacktPublishing/ASP.NET-Core-2-and-Vue.js#3]
Finished Chapter 3 was working on Chapter 4 and I am tetting the following:

"/ClientApp/components/App.vue
Module parse failed: C:\Users\1801\ECommerce\ClientApp\components\App.vue Unexpected token (1:0)
You may need an appropriate loader to handle this file type."

Not sure what is causing this and my Googleing has failed to come up with a solutino that works.

-Thanks

**Comment by spnm** [comment]
I have also a similar problem with webpack. It doesn't watch the changes in vue files. I have to re-run the project every time.

**Comment by spnm** [comment]
@diverjasongray did you update npm packages?

**Comment by spnm** [comment]
Here you are @sturatcliffe. The only changes i have made is that i used Sql Server instead of PostgreSQL and used .net core 2.1 instead of 2.0 (l[ink](https://github.com/spnm/ASP.NET-Core-2-and-Vue.js-1))

**Comment by diverjasongray** [comment]
In the webpack.config.js I added this line at the top as a rule and this
fixed it for me:

{ test: /\.vue$/, loader: 'vue-loader'},

**Comment by sturatcliffe** [comment]
@diverjasongray there should already be a rule that covers .vue files, see webpack.config.js file here: https://github.com/PacktPublishing/ASP.NET-Core-2-and-Vue.js/blob/chapter4/webpack.config.js

The only difference between yours and the one I've linked to is mine only looks in the ClientApp folder - if you have your client files in a different folder in won't work.

@spnm I've cloned your repo and everything works perfectly for me. However, I'm not convinced you've linked me to the right repo as you said you had updated to .NET Core 2.1, and were using SQL server. The repo I cloned still used PostgreSQL and .NET Core 2.0.

If the only issue you have is the HMR module is not running, i.e. you have to rebuild the client app after changing files, can you double check that you are running in development rather than production? The HMR module is only set to run in development.

Closing this issue as what you are seeing is different to @diverjasongray issue.

**Comment by spnm** [comment]
@sturatcliffe  I linked you to the right [repo](https://github.com/spnm/ASP.NET-Core-2-and-Vue.js-1). Check .[csproj ](https://github.com/spnm/ASP.NET-Core-2-and-Vue.js-1/blob/master/ECommerce.csproj)

**Comment by diverjasongray** [comment]
Mine was not building in Chapter 3. I abandoned the original project I
started. Even switched to my MacBook Pro. Could not get the project to
build. After a few days of research I saw someone add that line and it
works fine now. I had to add the line previously mentioned above in order
to get rid of the error. My Webpack looked exactly like the one cited but
with my line added to the top. Works - I dunno -- Can't really explain
it... But looked like someone else had the same error in a forum I searched.

**Comment by sturatcliffe** [comment]
I'd still guess that you're running with ASPNETCORE_ENVIRONMENT set to production rather than development. If you aren't running in development, the webpack middleware will not run and you'll need to rebuild the client app (as you are doing with the commands above) after each change.

Look at the `Configure` method at the top of `Startup.cs` here: https://github.com/PacktPublishing/ASP.NET-Core-2-and-Vue.js/blob/master/Startup.cs

The webpack middleware only runs if your environment is set to development:

```
if (env.IsDevelopment())
{
  app.UseDeveloperExceptionPage();
  app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
  {
    HotModuleReplacement = true
  });
}
else
{
  app.UseExceptionHandler("/Home/Error");
}
```

**Comment by spnm** [comment]
@sturatcliffe you are right! I had to use dotnet run environment=development. Thank you very much !!!

**Comment by sturatcliffe** [comment]
@spnm no problem - also worked out why my fork of your repo didn't work - I already had one forked with the same name so all I did was clone my original repo - oops!

2.1 was not out when I built the app and wrote the book, so unfortunately I can't guarantee that everything will work for you on that version. However, I have had a quick look through your app so far and the only thing I can see is that you are still using the Microsoft.AspNetCore.All metapackage - in 2.1 this was replaced with Microsoft.AspNetCore.App which needs no specific version number defining. 

I'd recommend going through this article to make sure your upgrade from 2.0 to 2.1 is fully complete: https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1

**Comment by diverjasongray** [comment]
I verified that the Startup.cs is exactuly how you have it. I get an error
without the line I added, and I don't get an error when I add the line.

Very strange - sorry to be a pain in the side. It seems like everytime I
try one of these projects, something has changed and it becomes more
difficult than it should be.

Jason

**Comment by diverjasongray** [comment]
Stu:

One last update - it seems that I had two refferences in the
webpack.config.vendor.js to use bootstrap. Your code works fine now. I
discovered this working chapter 5. Sorry for the troubles.

Jason

**Comment by sturatcliffe** [comment]
@diverjasongray sounds like you're sorted, but please feel free to link me to a Github repo if you want me to have a check over and make sure everything looks OK!

As for the previous comment around the Startup.cs file, I think this issue has been confused somewhat by having multiple different issues from different people. If you have any further problems please start a new issue and we'll make sure it stays on topic.
