### ISSUE TITLE
App errors if more than 2 of same product are added to cart

### ISSUE THREAD

**Issue by bryanleonard** [PacktPublishing/ASP.NET-Core-2-and-Vue.js#7]
Hi! I noticed that the app errors out if there are 2 of a given product already in the cart and the user clicks "Add to cart" an additional time. 

```javascript
[Vue warn]: Error in v-on handler: "TypeError: cartItem is undefined"

found in

---> <ProductDetails> at /Users/<UserName>/Desktop/ASPDotNETCore2andVuejs_Code/chapter 9/ClientApp/components/product/Details.vue
       <Product> at /Users/<UserName>/Desktop/ASPDotNETCore2andVuejs_Code/chapter 9/ClientApp/pages/Product.vue
         <App> at /Users/<UserName>/Desktop/ASPDotNETCore2andVuejs_Code/chapter 9/ClientApp/components/App.vue
           <Root> vendor.js:4044:7
TypeError: "cartItem is undefined"
    updateProductQuantity mutations.js:9
    wrappedMutationHandler vendor.js:31096
    commitIterator vendor.js:30762
    commit vendor.js:30761
    _withCommit vendor.js:30892
    commit vendor.js:30760
    boundCommit vendor.js:30705
    addProductToCart actions.js:12
    wrappedActionHandler vendor.js:31103
    dispatch vendor.js:30808
    boundDispatch vendor.js:30702
    addProductToCart Details.vue:115
    invokeWithErrorHandling vendor.js:5277
    invoker vendor.js:5598
    _wrapper vendor.js:10334
```

This can be reproduced in the sample code (at least through Chapter 9.)

How can this be fixed?

**Comment by sturatcliffe** [comment]
Apologies, my partner and I had a baby a few weeks ago, so I've only just returned to work or even used a computer in weeks! I'll look at this as soon as I can and get back to you!

**Comment by bryanleonard** [comment]
Congratulations! That's fantastic for you both. Best wishes on the new addition. 
(My apologies, if I knew how to fix this, I would've submitted a pull request and tried to save you the effort.)

**Comment by sturatcliffe** [comment]
Hey, I'm so sorry about how long it's taken to get this sorted out!

So it turns out this is a complete error on my part - I remember changing how the cart actions / mutations worked numerous times while writing the book, and what has happened is it looks like the latest version somehow didn't make its way up to master. It appears to be correct in all the chapter branches that I looked at, but it may be that I also missed updating the code sample in the actual book :(

If you look at the chapter12 branch as an example, the working actions / mutations are on there. I'll make sure they propagate all the way up to master.

To explain the issue a little, I'd imagine your ```updateProductQuantity``` mutation looks like this?:

```
export const updateProductQuantity = (state, product) => {
  const index = state.cart.indexOf(product);
  let cartItem = state.cart[index];
  cartItem.quantity++;

  state.cart.splice(index, 1, Object.assign({}, cartItem));
};
```

If so, the issue is that when we first add a product to the cart, the object that is passed in has a ```quantity``` property added to it. The next time the same product is added, we look for the index of that exact object within the cart array, but it isn't found as the quantity property does not exist. The correct way is to find the index of the existing product in the cart based on the composite key of the product, i.e. productId / colourId / storageId, then use the index to mutate the product in that position of the cart array. Hope this makes sense?

For me, I can't even add a second product in this way, as it errors immediately. I'm not sure why you would be able to add a second, but not a third product! However, take a look at the correct code and see if that fixes your issue. If not, link me to your code on github and I'll take a look!
